//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AchiveNoter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubThemeRel
    {
        public int ID { get; set; }
        public int SubThemeID { get; set; }
        public int ThemeID { get; set; }
    
        public virtual Subtheme Subtheme { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
