//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AchiveNoter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtheme
    {
        public Subtheme()
        {
            this.AchieveInfoes = new HashSet<AchieveInfo>();
            this.Themes = new HashSet<Theme>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AchieveInfo> AchieveInfoes { get; set; }
        public virtual ICollection<Theme> Themes { get; set; }
    }
}
