//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AchiveNoter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AchievmentsEntities : DbContext
    {
        public AchievmentsEntities()
            : base("name=AchievmentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AchieveInfo> AchieveInfoes { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<Subtheme> Subthemes { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<SubThemeRel> SubThemeRels { get; set; }
    }
}
